// import './normalize.css';
import Navigation from './components/Navigation';
import Portada from './components/Portada';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Navigation />
				<div className='portada w-full h-auto relative'>
					<Portada />
				</div>
				<div className='container mx-auto px-4'>{children}</div>
			</body>
		</html>
	);
}
